export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  WORKSPACE_HOME: "/workspace-home",
  SELECT_VESSEL: "/select-vessel",
  DASHBOARD: "/dashboard",
  CHECKLISTS: "/checklists",
  ISSUES: "/issues",
  HISTORY: "/history",
  PROFILE: "/profile",
  REPORTS: "/reports",
  CREW: "/crew",
  CREW_REQUESTS: "/crew/requests",
  QR_INVITE: "/crew/qr-invite",
  TEMPLATES: "/templates",
  ADMIN: "/admin",
  FLEET_DASHBOARD: "/admin/fleet",
  USERS_MANAGEMENT: "/admin/users",
  CAPTAINS_MANAGEMENT: "/admin/captains",
  VIP_VESSELS: "/admin/vip-vessels",
  GLOBAL_TEMPLATES: "/admin/global-templates",
  HEALTH_CHECK: "/admin/health-check",
  NOTIFICATIONS: "/notifications",
} as const;
